"""Grounded facet enrichment for decomposition entities/domains.

Expands aliases only when evidence appears in the query or existing facets.
Never invents geography, crops, or topics not grounded in user text.
"""
from __future__ import annotations

import re
from typing import Any

from ml.rag.chatbot.bq_table_schema_yaml import column_samples_for_table, match_value_samples

# Canonical corpus domain labels (aligned with domain_taxonomy / agri_measure_ontology).
_D_PROD = "Agricultural Production & Yield"
_D_TRADE = "Agricultural International Trade (Exports & Imports)"
_D_ECON = "Agricultural Economics"
_D_VALUE = "Agricultural Food Systems & Value Chain"
_D_MARKET = "Agricultural Market Access & Infrastructure"
_D_NUTR = "Agricultural Nutrition & Food Security"
_D_HUM = "Agricultural Humanitarian & Agricultural Emergency"
_D_CLIM = "Agricultural Environmental & Climate"
_D_SOIL = "Land Use & Soil Health"
_D_POL = "Agricultural Policy & Institutional"
_D_INV = "Agricultural Investment Readiness & Enterprise"
_D_TECH = "Agricultural Technology & Innovation"
_D_GEN = "Agricultural Gender, Youth & Inclusion"
_D_AGRI = "agriculture"

# (trigger, entity to add, optional domain tag)
# Prefer specific / multi-word triggers; matching is grounded in query+existing facets only.
_ENTITY_EXPAND: tuple[tuple[str, str, str | None], ...] = (
    # --- Food security / IPC / humanitarian / nutrition ---
    ("integrated food security phase classification", "food security", _D_NUTR),
    ("food security phase classification", "food security", _D_NUTR),
    ("food security phase", "food security", _D_NUTR),
    ("acute food insecurity", "food security", _D_NUTR),
    ("chronic food insecurity", "food security", _D_NUTR),
    ("food insecure", "food security", _D_NUTR),
    ("food insecurity", "food security", _D_NUTR),
    ("food security", "food security", _D_NUTR),
    ("food crisis", "food security", _D_HUM),
    ("hunger crisis", "food security", _D_HUM),
    ("humanitarian food", "food security", _D_HUM),
    ("crisis phase", "food security", _D_NUTR),
    ("emergency phase", "food security", _D_HUM),
    ("famine risk", "food security", _D_HUM),
    ("famine", "food security", _D_HUM),
    ("starvation", "food security", _D_HUM),
    ("hunger", "food security", _D_NUTR),
    ("ipc phase", "food security", _D_NUTR),
    ("ipc", "food security", _D_NUTR),
    ("fews net", "food security", _D_NUTR),
    ("fewsnet", "food security", _D_NUTR),
    ("fews", "food security", _D_NUTR),
    ("cadre harmonisé", "food security", _D_NUTR),
    ("cadre harmonise", "food security", _D_NUTR),
    ("wfp", "food security", _D_HUM),
    ("world food programme", "food security", _D_HUM),
    ("food aid", "humanitarian", _D_HUM),
    ("food assistance", "humanitarian", _D_HUM),
    ("cash transfer", "social protection", _D_HUM),
    ("cash transfers", "social protection", _D_HUM),
    ("safety net", "social protection", _D_HUM),
    ("social protection", "social protection", _D_HUM),
    ("school feeding", "nutrition", _D_NUTR),
    ("malnutrition", "malnutrition", _D_NUTR),
    ("undernutrition", "malnutrition", _D_NUTR),
    ("undernourishment", "malnutrition", _D_NUTR),
    ("stunting", "malnutrition", _D_NUTR),
    ("wasting", "malnutrition", _D_NUTR),
    ("underweight", "malnutrition", _D_NUTR),
    ("acute malnutrition", "malnutrition", _D_NUTR),
    ("severe acute malnutrition", "malnutrition", _D_NUTR),
    ("moderate acute malnutrition", "malnutrition", _D_NUTR),
    ("dietary diversity", "nutrition", _D_NUTR),
    ("micronutrient", "nutrition", _D_NUTR),
    ("micronutrients", "nutrition", _D_NUTR),
    ("fortification", "nutrition", _D_NUTR),
    ("biofortification", "nutrition", _D_NUTR),
    ("biofortified", "nutrition", _D_NUTR),
    ("nutrition-sensitive", "nutrition", _D_NUTR),
    ("nutrition", "nutrition", _D_NUTR),
    ("displacement", "humanitarian", _D_HUM),
    ("displaced", "humanitarian", _D_HUM),
    ("refugees", "humanitarian", _D_HUM),
    ("refugee", "humanitarian", _D_HUM),
    ("idps", "humanitarian", _D_HUM),
    ("idp", "humanitarian", _D_HUM),
    ("internally displaced", "humanitarian", _D_HUM),
    ("emergency response", "humanitarian", _D_HUM),
    ("humanitarian", "humanitarian", _D_HUM),
    ("conflict-affected", "humanitarian", _D_HUM),
    ("conflict", "humanitarian", _D_HUM),
    # --- Production / harvest / output ---
    ("harvest volume", "production", _D_PROD),
    ("tonnes produced", "production", _D_PROD),
    ("tons produced", "production", _D_PROD),
    ("produce the most", "production", _D_PROD),
    ("agricultural production", "production", _D_PROD),
    ("crop production", "production", _D_PROD),
    ("food production", "production", _D_PROD),
    ("livestock production", "livestock", _D_AGRI),
    ("production", "production", _D_PROD),
    ("output", "production", _D_PROD),
    ("harvest", "production", _D_PROD),
    ("harvested", "production", _D_PROD),
    ("produced", "production", _D_PROD),
    ("produces", "production", _D_PROD),
    ("tonnage", "production", _D_PROD),
    ("hectare", "production", _D_PROD),
    ("hectares", "production", _D_PROD),
    ("acreage", "production", _D_PROD),
    ("cultivated area", "cropland", _D_SOIL),
    ("planted area", "cropland", _D_SOIL),
    ("harvested area", "cropland", _D_SOIL),
    ("area harvested", "cropland", _D_SOIL),
    # --- Yield / productivity ---
    ("tonnes per hectare", "yield", _D_PROD),
    ("tons per hectare", "yield", _D_PROD),
    ("crop yield", "yield", _D_PROD),
    ("yield gap", "yield", _D_PROD),
    ("yields", "yield", _D_PROD),
    ("yield", "yield", _D_PROD),
    ("productivity", "yield", _D_PROD),
    ("t/ha", "yield", _D_PROD),
    ("kg/ha", "yield", _D_PROD),
    # --- Trade ---
    ("export volume", "trade", _D_TRADE),
    ("import volume", "trade", _D_TRADE),
    ("export value", "trade", _D_TRADE),
    ("import value", "trade", _D_TRADE),
    ("cross-border trade", "trade", _D_TRADE),
    ("cross border trade", "trade", _D_TRADE),
    ("informal trade", "trade", _D_TRADE),
    ("agricultural trade", "trade", _D_TRADE),
    ("agri-food trade", "trade", _D_TRADE),
    ("agrifood trade", "trade", _D_TRADE),
    ("self-sufficiency", "trade", _D_TRADE),
    ("self sufficiency", "trade", _D_TRADE),
    ("import dependency", "trade", _D_TRADE),
    ("terms of trade", "trade", _D_TRADE),
    ("exports", "trade", _D_TRADE),
    ("imports", "trade", _D_TRADE),
    ("export", "trade", _D_TRADE),
    ("import", "trade", _D_TRADE),
    ("re-export", "trade", _D_TRADE),
    ("traded", "trade", _D_TRADE),
    ("trade balance", "trade", _D_TRADE),
    ("trade deficit", "trade", _D_TRADE),
    ("trade surplus", "trade", _D_TRADE),
    ("trade", "trade", _D_TRADE),
    ("tariff", "trade", _D_TRADE),
    ("tariffs", "trade", _D_TRADE),
    ("non-tariff", "trade", _D_TRADE),
    ("customs", "trade", _D_TRADE),
    ("phytosanitary", "trade", _D_TRADE),
    ("sanitary and phytosanitary", "trade", _D_TRADE),
    ("sps measures", "trade", _D_TRADE),
    ("afcfta", "trade", _D_TRADE),
    ("african continental free trade", "trade", _D_TRADE),
    ("comesa", "trade", _D_TRADE),
    ("ecowas", "trade", _D_TRADE),
    ("sadc", "trade", _D_TRADE),
    ("eac trade", "trade", _D_TRADE),
    ("commodities trade", "trade", _D_TRADE),
    ("commodity trade", "trade", _D_TRADE),
    # --- Prices / markets / value chain ---
    ("retail prices", "market prices", _D_ECON),
    ("retail price", "market prices", _D_ECON),
    ("producer prices", "market prices", _D_ECON),
    ("producer price", "market prices", _D_ECON),
    ("commodity prices", "market prices", _D_ECON),
    ("commodity price", "market prices", _D_ECON),
    ("market prices", "market prices", _D_ECON),
    ("market price", "market prices", _D_ECON),
    ("farm gate", "market prices", _D_ECON),
    ("farm-gate", "market prices", _D_ECON),
    ("farmgate", "market prices", _D_ECON),
    ("wholesale price", "market prices", _D_ECON),
    ("wholesale prices", "market prices", _D_ECON),
    ("food prices", "market prices", _D_ECON),
    ("food price", "market prices", _D_ECON),
    ("price inflation", "market prices", _D_ECON),
    ("food inflation", "market prices", _D_ECON),
    ("prices", "market prices", _D_ECON),
    ("price", "market prices", _D_ECON),
    ("retail", "market prices", _D_ECON),
    ("wholesale", "market prices", _D_ECON),
    ("commodity exchange", "markets", _D_MARKET),
    ("warehouse receipt", "markets", _D_MARKET),
    ("marketplace", "markets", _D_MARKET),
    ("market access", "markets", _D_MARKET),
    ("market infrastructure", "markets", _D_MARKET),
    ("logistics", "markets", _D_MARKET),
    ("transport costs", "markets", _D_MARKET),
    ("storage", "markets", _D_MARKET),
    ("warehouse", "markets", _D_MARKET),
    ("value chain", "value chain", _D_VALUE),
    ("supply chain", "value chain", _D_VALUE),
    ("post-harvest loss", "value chain", _D_VALUE),
    ("post harvest loss", "value chain", _D_VALUE),
    ("post-harvest", "value chain", _D_VALUE),
    ("post harvest", "value chain", _D_VALUE),
    ("cold chain", "value chain", _D_VALUE),
    ("agro-processing", "value chain", _D_VALUE),
    ("agroprocessing", "value chain", _D_VALUE),
    ("food processing", "value chain", _D_VALUE),
    ("processing", "value chain", _D_VALUE),
    ("packaging", "value chain", _D_VALUE),
    ("traceability", "value chain", _D_VALUE),
    ("certification", "value chain", _D_VALUE),
    ("fairtrade", "value chain", _D_VALUE),
    ("organic certification", "value chain", _D_VALUE),
    # --- Staple cereals & grains ---
    ("maize", "maize", _D_PROD),
    ("corn", "maize", _D_PROD),
    ("rice", "rice", _D_PROD),
    ("paddy", "rice", _D_PROD),
    ("wheat", "wheat", _D_PROD),
    ("millet", "millet", _D_PROD),
    ("pearl millet", "millet", _D_PROD),
    ("finger millet", "millet", _D_PROD),
    ("sorghum", "sorghum", _D_PROD),
    ("teff", "teff", _D_PROD),
    ("fonio", "fonio", _D_PROD),
    ("barley", "barley", _D_PROD),
    ("oats", "oats", _D_PROD),
    ("rye", "rye", _D_PROD),
    ("quinoa", "quinoa", _D_PROD),
    ("amaranth", "amaranth", _D_PROD),
    ("cereal", "cereals", _D_PROD),
    ("cereals", "cereals", _D_PROD),
    ("grain", "cereals", _D_PROD),
    ("grains", "cereals", _D_PROD),
    ("staple crop", "staples", _D_PROD),
    ("staple crops", "staples", _D_PROD),
    ("staples", "staples", _D_PROD),
    # --- Roots, tubers, bananas, pulses ---
    ("cassava", "cassava", _D_PROD),
    ("manioc", "cassava", _D_PROD),
    ("yams", "yam", _D_PROD),
    ("yam", "yam", _D_PROD),
    ("taro", "taro", _D_PROD),
    ("cocoyam", "cocoyam", _D_PROD),
    ("cocoyams", "cocoyam", _D_PROD),
    ("enset", "enset", _D_PROD),
    ("false banana", "enset", _D_PROD),
    ("orange-fleshed sweet potato", "sweet potato", _D_PROD),
    ("orange fleshed sweet potato", "sweet potato", _D_PROD),
    ("ofsp", "sweet potato", _D_PROD),
    ("sweet potato", "sweet potato", _D_PROD),
    ("sweet potatoes", "sweet potato", _D_PROD),
    ("potato", "potato", _D_PROD),
    ("potatoes", "potato", _D_PROD),
    ("plantain", "plantain", _D_PROD),
    ("plantains", "plantain", _D_PROD),
    ("banana", "banana", _D_PROD),
    ("bananas", "banana", _D_PROD),
    ("beans", "beans", _D_PROD),
    ("common bean", "beans", _D_PROD),
    ("cowpea", "cowpea", _D_PROD),
    ("cowpeas", "cowpea", _D_PROD),
    ("bambara", "bambara groundnut", _D_PROD),
    ("bambara groundnut", "bambara groundnut", _D_PROD),
    ("pigeon pea", "pigeon pea", _D_PROD),
    ("pigeon peas", "pigeon pea", _D_PROD),
    ("chickpea", "chickpea", _D_PROD),
    ("chickpeas", "chickpea", _D_PROD),
    ("lentil", "lentil", _D_PROD),
    ("lentils", "lentil", _D_PROD),
    ("pulses", "pulses", _D_PROD),
    ("legumes", "pulses", _D_PROD),
    # --- Oilseeds, cash crops, industrial, horticulture ---
    ("soybeans", "soybean", _D_PROD),
    ("soybean", "soybean", _D_PROD),
    ("soya bean", "soybean", _D_PROD),
    ("soya", "soybean", _D_PROD),
    ("soy", "soybean", _D_PROD),
    ("groundnuts", "groundnut", _D_PROD),
    ("groundnut", "groundnut", _D_PROD),
    ("peanuts", "groundnut", _D_PROD),
    ("peanut", "groundnut", _D_PROD),
    ("sesame", "sesame", _D_PROD),
    ("sesame seed", "sesame", _D_PROD),
    ("sunflower", "sunflower", _D_PROD),
    ("rapeseed", "rapeseed", _D_PROD),
    ("canola", "rapeseed", _D_PROD),
    ("palm oil", "palm oil", _D_PROD),
    ("oil palm", "palm oil", _D_PROD),
    ("cotton", "cotton", _D_PROD),
    ("cocoa", "cocoa", _D_PROD),
    ("cacao", "cocoa", _D_PROD),
    ("coffee", "coffee", _D_PROD),
    ("arabica", "coffee", _D_PROD),
    ("robusta", "coffee", _D_PROD),
    ("tea", "tea", _D_PROD),
    ("sugarcane", "sugarcane", _D_PROD),
    ("sugar cane", "sugarcane", _D_PROD),
    ("tobacco", "tobacco", _D_PROD),
    ("rubber", "rubber", _D_PROD),
    ("cashew", "cashew", _D_PROD),
    ("cashews", "cashew", _D_PROD),
    ("shea", "shea", _D_PROD),
    ("shea butter", "shea", _D_PROD),
    ("vanilla", "vanilla", _D_PROD),
    ("cloves", "cloves", _D_PROD),
    ("clove", "cloves", _D_PROD),
    ("cinnamon", "cinnamon", _D_PROD),
    ("nutmeg", "nutmeg", _D_PROD),
    ("pyrethrum", "pyrethrum", _D_PROD),
    ("sisal", "sisal", _D_PROD),
    ("jute", "jute", _D_PROD),
    ("kenaf", "kenaf", _D_PROD),
    ("castor", "castor", _D_PROD),
    ("jatropha", "jatropha", _D_PROD),
    ("macadamia", "macadamia", _D_PROD),
    ("date palm", "dates", _D_PROD),
    ("dates", "dates", _D_PROD),
    ("olive", "olive", _D_PROD),
    ("olives", "olive", _D_PROD),
    ("grape", "grapes", _D_PROD),
    ("grapes", "grapes", _D_PROD),
    ("wine", "grapes", _D_PROD),
    ("pineapple", "pineapple", _D_PROD),
    ("papaya", "papaya", _D_PROD),
    ("pawpaw", "papaya", _D_PROD),
    ("guava", "guava", _D_PROD),
    ("passion fruit", "passion fruit", _D_PROD),
    ("watermelon", "watermelon", _D_PROD),
    ("melon", "melon", _D_PROD),
    ("mango", "mango", _D_PROD),
    ("mangoes", "mango", _D_PROD),
    ("avocado", "avocado", _D_PROD),
    ("avocados", "avocado", _D_PROD),
    ("citrus", "citrus", _D_PROD),
    ("orange", "citrus", _D_PROD),
    ("oranges", "citrus", _D_PROD),
    ("lemon", "citrus", _D_PROD),
    ("horticulture", "horticulture", _D_PROD),
    ("floriculture", "horticulture", _D_PROD),
    ("vegetables", "vegetables", _D_PROD),
    ("vegetable", "vegetables", _D_PROD),
    ("onion", "onion", _D_PROD),
    ("onions", "onion", _D_PROD),
    ("tomato", "tomato", _D_PROD),
    ("tomatoes", "tomato", _D_PROD),
    ("pepper", "pepper", _D_PROD),
    ("peppers", "pepper", _D_PROD),
    ("chili", "pepper", _D_PROD),
    ("chilli", "pepper", _D_PROD),
    ("okra", "okra", _D_PROD),
    ("eggplant", "eggplant", _D_PROD),
    ("aubergine", "eggplant", _D_PROD),
    ("cabbage", "cabbage", _D_PROD),
    ("carrot", "carrot", _D_PROD),
    ("garlic", "garlic", _D_PROD),
    ("ginger", "ginger", _D_PROD),
    ("turmeric", "turmeric", _D_PROD),
    ("kola", "kola", _D_PROD),
    ("cola nut", "kola", _D_PROD),
    ("moringa", "moringa", _D_PROD),
    ("baobab", "baobab", _D_PROD),
    ("neem", "neem", _D_PROD),
    ("fruit", "fruits", _D_PROD),
    ("fruits", "fruits", _D_PROD),
    ("cash crop", "cash crops", _D_PROD),
    ("cash crops", "cash crops", _D_PROD),
    ("export crop", "cash crops", _D_PROD),
    # --- Livestock / dairy / animal health ---
    ("livestock insurance", "livestock", _D_AGRI),
    ("animal health", "livestock", _D_AGRI),
    ("livestock", "livestock", _D_AGRI),
    ("ruminants", "livestock", _D_AGRI),
    ("cattle", "cattle", _D_AGRI),
    ("cows", "cattle", _D_AGRI),
    ("cow", "cattle", _D_AGRI),
    ("oxen", "cattle", _D_AGRI),
    ("bulls", "cattle", _D_AGRI),
    ("buffalo", "cattle", _D_AGRI),
    ("goats", "goats", _D_AGRI),
    ("goat", "goats", _D_AGRI),
    ("sheep", "sheep", _D_AGRI),
    ("camels", "camels", _D_AGRI),
    ("camel", "camels", _D_AGRI),
    ("donkeys", "donkeys", _D_AGRI),
    ("donkey", "donkeys", _D_AGRI),
    ("horses", "horses", _D_AGRI),
    ("pigs", "pigs", _D_AGRI),
    ("swine", "pigs", _D_AGRI),
    ("pork", "pigs", _D_AGRI),
    ("poultry", "poultry", _D_AGRI),
    ("chicken", "poultry", _D_AGRI),
    ("chickens", "poultry", _D_AGRI),
    ("broiler", "poultry", _D_AGRI),
    ("layers", "poultry", _D_AGRI),
    ("eggs", "poultry", _D_AGRI),
    ("ducks", "poultry", _D_AGRI),
    ("turkey", "poultry", _D_AGRI),
    ("guinea fowl", "poultry", _D_AGRI),
    ("dairy", "dairy", _D_AGRI),
    ("milk", "dairy", _D_AGRI),
    ("beef", "cattle", _D_AGRI),
    ("meat", "livestock", _D_AGRI),
    ("beekeeping", "beekeeping", _D_AGRI),
    ("apiculture", "beekeeping", _D_AGRI),
    ("honey", "beekeeping", _D_AGRI),
    ("pastoral", "pastoralism", _D_AGRI),
    ("pastoralism", "pastoralism", _D_AGRI),
    ("pastoralist", "pastoralism", _D_AGRI),
    ("pastoralists", "pastoralism", _D_AGRI),
    ("transhumance", "pastoralism", _D_AGRI),
    ("herders", "pastoralism", _D_AGRI),
    ("herding", "pastoralism", _D_AGRI),
    ("rangeland", "pastoralism", _D_AGRI),
    ("rangelands", "pastoralism", _D_AGRI),
    ("fodder", "feed", _D_AGRI),
    ("forage", "feed", _D_AGRI),
    ("silage", "feed", _D_AGRI),
    ("animal feed", "feed", _D_AGRI),
    ("feed", "feed", _D_AGRI),
    ("veterinary", "animal health", _D_AGRI),
    ("zoonotic", "animal health", _D_AGRI),
    ("zoonoses", "animal health", _D_AGRI),
    ("vaccination", "animal health", _D_AGRI),
    ("vaccine", "animal health", _D_AGRI),
    ("peste des petits ruminants", "animal health", _D_AGRI),
    ("foot and mouth", "animal health", _D_AGRI),
    ("foot-and-mouth", "animal health", _D_AGRI),
    ("trypanosomiasis", "animal health", _D_AGRI),
    ("tsetse", "animal health", _D_AGRI),
    ("tick-borne", "animal health", _D_AGRI),
    ("east coast fever", "animal health", _D_AGRI),
    ("rift valley fever", "animal health", _D_AGRI),
    ("african swine fever", "animal health", _D_AGRI),
    ("avian influenza", "animal health", _D_AGRI),
    ("newcastle disease", "animal health", _D_AGRI),
    ("brucellosis", "animal health", _D_AGRI),
    ("anthrax", "animal health", _D_AGRI),
    ("rabies", "animal health", _D_AGRI),
    # --- Fisheries / aquaculture / blue economy ---
    ("aquaculture", "aquaculture", _D_PROD),
    ("fish farming", "aquaculture", _D_PROD),
    ("mariculture", "aquaculture", _D_PROD),
    ("fisheries", "fisheries", _D_PROD),
    ("fishery", "fisheries", _D_PROD),
    ("inland fish", "fisheries", _D_PROD),
    ("capture fish", "fisheries", _D_PROD),
    ("artisanal fish", "fisheries", _D_PROD),
    ("blue economy", "fisheries", _D_PROD),
    ("iuu fishing", "fisheries", _D_PROD),
    ("overfishing", "fisheries", _D_PROD),
    ("tilapia", "tilapia", _D_PROD),
    ("catfish", "catfish", _D_PROD),
    ("nile perch", "nile perch", _D_PROD),
    ("shrimp", "shrimp", _D_PROD),
    ("prawn", "shrimp", _D_PROD),
    ("seaweed", "seaweed", _D_PROD),
    # --- Forestry / agroforestry ---
    ("agroforestry", "agroforestry", _D_CLIM),
    ("forestry", "forestry", _D_CLIM),
    ("deforestation", "forestry", _D_CLIM),
    ("afforestation", "forestry", _D_CLIM),
    ("reforestation", "forestry", _D_CLIM),
    ("woodland", "forestry", _D_CLIM),
    ("charcoal", "forestry", _D_CLIM),
    ("fuelwood", "forestry", _D_CLIM),
    ("firewood", "forestry", _D_CLIM),
    ("timber", "forestry", _D_CLIM),
    ("mangrove", "forestry", _D_CLIM),
    ("mangroves", "forestry", _D_CLIM),
    # --- Climate / weather / water ---
    ("rainy season", "climate", _D_CLIM),
    ("dry season", "climate", _D_CLIM),
    ("climate change", "climate", _D_CLIM),
    ("climate shock", "climate", _D_CLIM),
    ("climate risk", "climate", _D_CLIM),
    ("climate resilience", "climate", _D_CLIM),
    ("extreme weather", "climate", _D_CLIM),
    ("precipitation", "climate", _D_CLIM),
    ("rainfall", "climate", _D_CLIM),
    ("temperature", "climate", _D_CLIM),
    ("drought", "climate", _D_CLIM),
    ("dry spell", "climate", _D_CLIM),
    ("flooding", "climate", _D_CLIM),
    ("floods", "climate", _D_CLIM),
    ("flood", "climate", _D_CLIM),
    ("cyclone", "climate", _D_CLIM),
    ("tropical storm", "climate", _D_CLIM),
    ("weather", "climate", _D_CLIM),
    ("climate", "climate", _D_CLIM),
    ("el niño", "climate", _D_CLIM),
    ("el nino", "climate", _D_CLIM),
    ("la niña", "climate", _D_CLIM),
    ("la nina", "climate", _D_CLIM),
    ("enso", "climate", _D_CLIM),
    ("heatwave", "climate", _D_CLIM),
    ("heat stress", "climate", _D_CLIM),
    ("late onset", "climate", _D_CLIM),
    ("false start", "climate", _D_CLIM),
    ("ndvi", "vegetation", _D_CLIM),
    ("vegetation index", "vegetation", _D_CLIM),
    ("evapotranspiration", "climate", _D_CLIM),
    ("drip irrigation", "irrigation", _D_CLIM),
    ("irrigation", "irrigation", _D_CLIM),
    ("irrigated", "irrigation", _D_CLIM),
    ("rainfed", "irrigation", _D_CLIM),
    ("rain-fed", "irrigation", _D_CLIM),
    ("water scarcity", "water", _D_CLIM),
    ("water stress", "water", _D_CLIM),
    ("groundwater", "water", _D_CLIM),
    ("borehole", "water", _D_CLIM),
    ("boreholes", "water", _D_CLIM),
    ("watershed", "water", _D_CLIM),
    ("river basin", "water", _D_CLIM),
    ("reservoir", "water", _D_CLIM),
    ("wetland", "water", _D_CLIM),
    ("wetlands", "water", _D_CLIM),
    ("hydrology", "water", _D_CLIM),
    # --- Soil / land / degradation ---
    ("soil organic matter", "soil", _D_SOIL),
    ("soil organic carbon", "soil", _D_SOIL),
    ("soil organic", "soil", _D_SOIL),
    ("soil health", "soil", _D_SOIL),
    ("soil fertility", "soil", _D_SOIL),
    ("organic matter", "soil", _D_SOIL),
    ("land degradation", "land degradation", _D_SOIL),
    ("desertification", "land degradation", _D_SOIL),
    ("soil erosion", "land degradation", _D_SOIL),
    ("erosion", "land degradation", _D_SOIL),
    ("salinization", "land degradation", _D_SOIL),
    ("salinity", "land degradation", _D_SOIL),
    ("degradation", "land degradation", _D_SOIL),
    ("fertility", "soil", _D_SOIL),
    ("nutrients", "soil", _D_SOIL),
    ("nutrient", "soil", _D_SOIL),
    ("soil", "soil", _D_SOIL),
    ("cropland", "cropland", _D_SOIL),
    ("agricultural land", "cropland", _D_SOIL),
    ("arable land", "cropland", _D_SOIL),
    ("agricultural activities", "agricultural activities", _D_PROD),
    ("agri activities", "agricultural activities", _D_PROD),
    ("country by country", "agricultural activities", _D_PROD),
    ("wdpa", "protected areas", _D_SOIL),
    ("protected planet", "protected areas", _D_SOIL),
    ("food balance", "food balance", _D_PROD),
    ("import dependency", "food balance", _D_PROD),
    ("land use", "land use", _D_SOIL),
    ("land cover", "land use", _D_SOIL),
    ("protected areas", "biodiversity", _D_SOIL),
    ("biodiversity", "biodiversity", _D_SOIL),
    ("germplasm", "germplasm", _D_TECH),
    ("tenure", "land tenure", _D_POL),
    ("land rights", "land tenure", _D_POL),
    ("land tenure", "land tenure", _D_POL),
    ("land grab", "land tenure", _D_POL),
    # --- Inputs / fertilizer / seeds ---
    ("fertilizer", "fertilizer", _D_SOIL),
    ("fertiliser", "fertilizer", _D_SOIL),
    ("fertilizers", "fertilizer", _D_SOIL),
    ("fertilisers", "fertilizer", _D_SOIL),
    ("organic fertilizer", "fertilizer", _D_SOIL),
    ("synthetic fertilizer", "fertilizer", _D_SOIL),
    ("urea", "fertilizer", _D_SOIL),
    ("nitrogen", "fertilizer", _D_SOIL),
    ("phosphorus", "fertilizer", _D_SOIL),
    ("potassium", "fertilizer", _D_SOIL),
    ("npk", "fertilizer", _D_SOIL),
    ("compost", "fertilizer", _D_SOIL),
    ("manure", "fertilizer", _D_SOIL),
    ("lime", "fertilizer", _D_SOIL),
    ("seed system", "seeds", _D_PROD),
    ("improved seed", "seeds", _D_PROD),
    ("certified seed", "seeds", _D_PROD),
    ("hybrid seed", "seeds", _D_PROD),
    ("seeds", "seeds", _D_PROD),
    ("seed", "seeds", _D_PROD),
    ("pesticide", "pesticides", _D_PROD),
    ("pesticides", "pesticides", _D_PROD),
    ("herbicide", "pesticides", _D_PROD),
    ("insecticide", "pesticides", _D_PROD),
    ("fungicide", "pesticides", _D_PROD),
    ("biopesticide", "pesticides", _D_PROD),
    ("agrochemical", "pesticides", _D_PROD),
    ("agrochemicals", "pesticides", _D_PROD),
    ("inputs", "inputs", _D_SOIL),
    ("input subsidy", "subsidy", _D_POL),
    ("mechanization", "mechanization", _D_TECH),
    ("mechanisation", "mechanization", _D_TECH),
    ("tractor", "mechanization", _D_TECH),
    ("tractors", "mechanization", _D_TECH),
    ("combine harvester", "mechanization", _D_TECH),
    # --- Pests / diseases / plant health ---
    ("fall armyworm", "pests", _D_PROD),
    ("army worm", "pests", _D_PROD),
    ("armyworm", "pests", _D_PROD),
    ("desert locust", "pests", _D_PROD),
    ("locust swarm", "pests", _D_PROD),
    ("locust", "pests", _D_PROD),
    ("quelea", "pests", _D_PROD),
    ("stem borer", "pests", _D_PROD),
    ("whitefly", "pests", _D_PROD),
    ("aphid", "pests", _D_PROD),
    ("weevil", "pests", _D_PROD),
    ("cassava mosaic", "plant disease", _D_PROD),
    ("banana wilt", "plant disease", _D_PROD),
    ("maize lethal necrosis", "plant disease", _D_PROD),
    ("plant disease", "plant disease", _D_PROD),
    ("crop disease", "plant disease", _D_PROD),
    ("rust disease", "plant disease", _D_PROD),
    ("blight", "plant disease", _D_PROD),
    ("wilt", "plant disease", _D_PROD),
    ("pest", "pests", _D_PROD),
    ("pests", "pests", _D_PROD),
    ("invasive species", "pests", _D_PROD),
    ("integrated pest management", "pests", _D_PROD),
    ("ipm", "pests", _D_PROD),
    # --- Emissions / GHG ---
    ("greenhouse gas", "emissions", _D_CLIM),
    ("carbon from agriculture", "emissions", _D_CLIM),
    ("carbon emissions", "emissions", _D_CLIM),
    ("methane", "emissions", _D_CLIM),
    ("nitrous oxide", "emissions", _D_CLIM),
    ("emissions", "emissions", _D_CLIM),
    ("ghg", "emissions", _D_CLIM),
    ("carbon sequestration", "emissions", _D_CLIM),
    ("carbon sink", "emissions", _D_CLIM),
    ("net zero", "emissions", _D_CLIM),
    # --- Socio-economic ---
    ("gross domestic product", "gdp", _D_ECON),
    ("gdp", "gdp", _D_ECON),
    ("economies", "economy", _D_ECON),
    ("economy", "economy", _D_ECON),
    ("economic growth", "economy", _D_ECON),
    ("rural economy", "economy", _D_ECON),
    ("farm income", "income", _D_ECON),
    ("hdi", "hdi", _D_ECON),
    ("human development", "hdi", _D_ECON),
    ("employment", "employment", _D_ECON),
    ("unemployment", "employment", _D_ECON),
    ("jobs", "employment", _D_ECON),
    ("livelihoods", "livelihoods", _D_ECON),
    ("livelihood", "livelihoods", _D_ECON),
    ("poverty", "poverty", _D_ECON),
    ("income", "income", _D_ECON),
    ("remittances", "income", _D_ECON),
    ("remittance", "income", _D_ECON),
    ("inflation", "market prices", _D_ECON),
    ("population", "population", _D_ECON),
    ("demographics", "population", _D_ECON),
    ("urbanization", "population", _D_ECON),
    ("urbanisation", "population", _D_ECON),
    ("rural", "rural", _D_ECON),
    ("development", "development", _D_POL),
    ("sdg", "sdg", _D_POL),
    ("sustainable development", "sdg", _D_POL),
    # --- Investment / finance / ASTI ---
    ("agricultural research spending", "investment", _D_INV),
    ("investment in agriculture research", "investment", _D_INV),
    ("agri finance", "investment", _D_INV),
    ("agricultural finance", "investment", _D_INV),
    ("agri investment", "investment", _D_INV),
    ("agricultural investment", "investment", _D_INV),
    ("r&d spend", "investment", _D_INV),
    ("research spending", "investment", _D_INV),
    ("asti", "investment", _D_INV),
    ("investment", "investment", _D_INV),
    ("blended finance", "finance", _D_INV),
    ("impact investment", "finance", _D_INV),
    ("impact investing", "finance", _D_INV),
    ("venture capital", "finance", _D_INV),
    ("private equity", "finance", _D_INV),
    ("credit", "finance", _D_INV),
    ("loan", "finance", _D_INV),
    ("loans", "finance", _D_INV),
    ("microfinance", "finance", _D_INV),
    ("mobile money", "finance", _D_INV),
    ("fintech", "finance", _D_INV),
    ("insurance", "insurance", _D_INV),
    ("index insurance", "insurance", _D_INV),
    ("weather insurance", "insurance", _D_INV),
    ("crop insurance", "insurance", _D_INV),
    ("subsidy", "subsidy", _D_POL),
    ("subsidies", "subsidy", _D_POL),
    ("fdi", "investment", _D_INV),
    ("foreign direct investment", "investment", _D_INV),
    ("where to invest in agriculture", "investment", _D_INV),
    ("where to invest in agri", "investment", _D_INV),
    ("investment attractiveness", "investment", _D_INV),
    ("funding", "investment", _D_INV),
    # --- Policy / institutions ---
    ("agricultural policy", "policy", _D_POL),
    ("food policy", "policy", _D_POL),
    ("public policy", "policy", _D_POL),
    ("policies", "policy", _D_POL),
    ("policy", "policy", _D_POL),
    ("regulation", "policy", _D_POL),
    ("regulatory", "policy", _D_POL),
    ("legislation", "policy", _D_POL),
    ("governance", "policy", _D_POL),
    ("ministry of agriculture", "policy", _D_POL),
    ("national agriculture investment plan", "policy", _D_POL),
    ("naip", "policy", _D_POL),
    ("caadp", "policy", _D_POL),
    ("malabo", "policy", _D_POL),
    ("maputo declaration", "policy", _D_POL),
    ("agenda 2063", "policy", _D_POL),
    ("ndc", "policy", _D_CLIM),
    ("nationally determined contribution", "policy", _D_CLIM),
    ("adaptation plan", "policy", _D_CLIM),
    # --- Extension / practices ---
    ("extension services", "extension", _D_POL),
    ("agricultural extension", "extension", _D_POL),
    ("e-extension", "extension", _D_TECH),
    ("extension", "extension", _D_POL),
    ("agronomic practice", "practices", _D_PROD),
    ("best practice", "practices", _D_PROD),
    ("farming practice", "practices", _D_PROD),
    ("conservation agriculture", "practices", _D_SOIL),
    ("agroecology", "practices", _D_CLIM),
    ("climate-smart", "practices", _D_CLIM),
    ("climate smart", "practices", _D_CLIM),
    ("climate-smart agriculture", "practices", _D_CLIM),
    ("intercropping", "practices", _D_PROD),
    ("crop rotation", "practices", _D_PROD),
    ("cover crop", "practices", _D_SOIL),
    ("cover crops", "practices", _D_SOIL),
    ("no-till", "practices", _D_SOIL),
    ("minimum tillage", "practices", _D_SOIL),
    ("farmer field school", "extension", _D_POL),
    ("how to plant", "practices", _D_PROD),
    ("how to grow", "practices", _D_PROD),
    # --- Technology / digital / innovation ---
    ("precision agriculture", "agtech", _D_TECH),
    ("digital agriculture", "agtech", _D_TECH),
    ("agtech", "agtech", _D_TECH),
    ("agri-tech", "agtech", _D_TECH),
    ("agritech", "agtech", _D_TECH),
    ("remote sensing", "agtech", _D_TECH),
    ("earth observation", "agtech", _D_TECH),
    ("satellite", "agtech", _D_TECH),
    ("drone", "agtech", _D_TECH),
    ("drones", "agtech", _D_TECH),
    ("iot", "agtech", _D_TECH),
    ("gis", "agtech", _D_TECH),
    ("blockchain", "agtech", _D_TECH),
    ("innovation", "innovation", _D_TECH),
    ("biotechnology", "innovation", _D_TECH),
    ("gmo", "innovation", _D_TECH),
    ("genetically modified", "innovation", _D_TECH),
    ("tissue culture", "innovation", _D_TECH),
    # --- Gender / youth / inclusion ---
    ("women farmers", "gender", _D_GEN),
    ("female farmers", "gender", _D_GEN),
    ("women in agriculture", "gender", _D_GEN),
    ("gender", "gender", _D_GEN),
    ("youth employment", "youth", _D_GEN),
    ("youth in agriculture", "youth", _D_GEN),
    ("youth", "youth", _D_GEN),
    ("young farmers", "youth", _D_GEN),
    ("inclusion", "inclusion", _D_GEN),
    ("smallholder", "smallholders", _D_GEN),
    ("smallholders", "smallholders", _D_GEN),
    ("small-scale", "smallholders", _D_GEN),
    ("outgrower", "smallholders", _D_VALUE),
    ("contract farming", "smallholders", _D_VALUE),
    ("cooperative", "cooperatives", _D_VALUE),
    ("cooperatives", "cooperatives", _D_VALUE),
    ("farmer organization", "cooperatives", _D_VALUE),
    ("farmer organisation", "cooperatives", _D_VALUE),
    ("producer organization", "cooperatives", _D_VALUE),
    # --- Research / evidence / briefing ---
    ("peer-reviewed", "research", _D_TECH),
    ("peer reviewed", "research", _D_TECH),
    ("literature", "research", _D_TECH),
    ("academic research", "research", _D_TECH),
    ("academic", "research", _D_TECH),
    ("research projects", "research", _D_TECH),
    ("research", "research", _D_TECH),
    ("publications", "research", _D_TECH),
    ("openaire", "research", _D_TECH),
    ("evidence", "research", _D_TECH),
    ("briefing", "briefing", _D_AGRI),
    ("headlines", "briefing", _D_AGRI),
    ("what's new", "briefing", _D_AGRI),
    ("latest news", "briefing", _D_AGRI),
    ("situation update", "briefing", _D_AGRI),
    # --- Agribusiness / enterprise / food systems ---
    ("agribusiness", "agribusiness", _D_AGRI),
    ("agro-business", "agribusiness", _D_AGRI),
    ("agrobusiness", "agribusiness", _D_AGRI),
    ("agripreneur", "agribusiness", _D_INV),
    ("agri-entrepreneur", "agribusiness", _D_INV),
    ("entrepreneur", "agribusiness", _D_INV),
    ("startup", "agribusiness", _D_INV),
    ("start-up", "agribusiness", _D_INV),
    ("farm enterprise", "agribusiness", _D_INV),
    ("commercial farming", "agribusiness", _D_AGRI),
    ("plantation", "agribusiness", _D_AGRI),
    ("farming", "farming", _D_AGRI),
    ("agriculture", "agriculture", _D_AGRI),
    ("agricultural", "agriculture", _D_AGRI),
    ("agrifood", "agribusiness", _D_VALUE),
    ("agro-food", "agribusiness", _D_VALUE),
    ("food system", "food systems", _D_VALUE),
    ("food systems", "food systems", _D_VALUE),
)


def _trigger_in_blob(trigger: str, blob: str) -> bool:
    t = (trigger or "").lower().strip()
    if not t:
        return False
    if " " in t or "/" in t:
        return t in blob
    return bool(re.search(rf"\b{re.escape(t)}\b", blob, flags=re.IGNORECASE))


# Role → (dim_table, label_column) — samples only; never invent labels.
_ENTITY_ROLE_DIMS: dict[str, tuple[str, str]] = {
    "land_use": ("dim_land_use", "land_use_code"),
    "hazard": ("dim_disease", "disease_or_hazard"),
    "item": ("dim_item", "item_name"),
    "pest": ("dim_pest", "pest_name"),
    "season": ("dim_season", "season_name"),
    "livestock": ("dim_livestock", "species"),
}


def ground_entity_roles(
    query: str,
    *,
    entities: list[str] | None = None,
) -> dict[str, list[str]]:
    """Match query/entities against dim sample dictionaries for typed roles."""
    blob = " ".join(
        [
            (query or "").strip(),
            *[str(e).strip() for e in (entities or []) if str(e).strip()],
        ]
    )
    if not blob.strip():
        return {}
    out: dict[str, list[str]] = {}
    for role, (dim_table, dim_col) in _ENTITY_ROLE_DIMS.items():
        samples = column_samples_for_table(dim_table, dim_col)
        if not samples:
            continue
        matched = match_value_samples(blob, samples)
        labels: list[str] = []
        seen: set[str] = set()
        for raw in matched:
            lab = str(raw).strip()
            if not lab or lab.lower() in seen:
                continue
            seen.add(lab.lower())
            labels.append(lab)
            if len(labels) >= 3:
                break
        if labels:
            out[role] = labels
    return out


def enrich_decomposition_facets(
    query: str,
    decomposition: dict[str, Any] | None,
) -> dict[str, Any]:
    """
    Return a copy of decomposition with grounded entity/domain expansions.

    Only adds labels whose triggers appear in the query or existing facet strings.
    """
    out = dict(decomposition or {})
    q = (query or "").strip()
    ql = q.lower()
    entities = [str(e).strip() for e in (out.get("entities") or []) if str(e).strip()]
    domains = [str(d).strip() for d in (out.get("domains") or []) if str(d).strip()]
    existing_blob = " ".join([ql, *[e.lower() for e in entities], *[d.lower() for d in domains]])

    ent_l = {e.lower() for e in entities}
    dom_l = {d.lower() for d in domains}

    for trigger, entity, domain in _ENTITY_EXPAND:
        if not _trigger_in_blob(trigger, existing_blob):
            continue
        if entity.lower() not in ent_l:
            entities.append(entity)
            ent_l.add(entity.lower())
        if domain and domain.lower() not in dom_l:
            domains.append(domain)
            dom_l.add(domain.lower())

    out["entities"] = entities[:48]
    out["domains"] = domains[:24]

    roles = ground_entity_roles(q, entities=entities)
    if roles:
        existing_roles = out.get("entity_roles")
        merged: dict[str, list[str]] = {}
        if isinstance(existing_roles, dict):
            for k, v in existing_roles.items():
                labs = [str(x).strip() for x in (v or []) if str(x).strip()]
                if labs:
                    merged[str(k).strip().lower()] = labs
        for role, labs in roles.items():
            if role not in merged:
                merged[role] = labs
        out["entity_roles"] = merged
    return out


__all__ = ["enrich_decomposition_facets", "ground_entity_roles"]
