#!/usr/bin/env python3
"""
Generate dbt/models/sources.yml from the BigQuery schema catalog so dbt stays in sync
with BQ without hand-maintaining table/column lists. Run after refreshing the catalog.

Usage:
  From repo root:
    python data/local/scripts/bq_schema_catalog.py   # refresh BQ schema catalog
    python data/local/scripts/generate_dbt_sources.py  # generate dbt sources from catalog

  Or refresh catalog then generate in one go:
    python data/local/scripts/generate_dbt_sources.py --refresh

  If docs/bq_schema_catalog.json is missing, writes a minimal sources.yml (placeholder
  tables) so dbt parses; re-run after bq_schema_catalog.py for full tables/columns.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
CATALOG_PATH = REPO_ROOT / "docs" / "bq_schema_catalog.json"
DBT_SOURCES_PATH = REPO_ROOT / "dbt" / "models" / "sources.yml"

LAYER_DESCRIPTIONS = {
    "landing": "Raw landing data (ingestion writes here)",
    "bronze": "Bronze database (raw, immutable)",
    "silver": "Silver database (cleaned, normalized)",
    "gold": "Gold database (ML & analytics ready)",
}

VAR_NAMES = {
    "landing": "landing_dataset",
    "bronze": "bronze_dataset",
    "silver": "silver_dataset",
    "gold": "gold_dataset",
}


def load_catalog() -> dict | None:
    if not CATALOG_PATH.exists():
        return None
    return json.loads(CATALOG_PATH.read_text(encoding="utf-8"))


def build_sources_yml(catalog: dict) -> str:
    """Build dbt sources.yml content from catalog (database/schema from env vars)."""
    lines = [
        "# Generated by data/local/scripts/generate_dbt_sources.py from docs/bq_schema_catalog.json",
        "# Do not edit by hand; re-run the script after BQ schema changes.",
        "",
        "version: 2",
        "",
        "sources:",
    ]
    for layer in ("landing", "bronze", "silver", "gold"):
        data = catalog.get("datasets", {}).get(layer, {})
        tables = data.get("tables", [])
        desc = LAYER_DESCRIPTIONS[layer]

        # Map each logical layer to its dataset env var
        if layer == "landing":
            schema_env = "BQ_DATASET_LANDING"
        elif layer == "bronze":
            schema_env = "BQ_DATASET_BRONZE"
        elif layer == "silver":
            schema_env = "BQ_DATASET_SILVER"
        else:  # gold
            schema_env = "BQ_DATASET_GOLD"

        lines.append(f"  - name: {layer}")
        lines.append('    database: "{{ env_var(\'BQ_PROJECT\', \'opentrace-prod-5ga4\') }}"')
        # Use Jinja directly: {{ env_var('BQ_DATASET_*', 'default') }}
        lines.append(
            "    schema: \"{{ env_var('" + schema_env + "', '" + layer + "') }}\""
        )
        lines.append(f"    description: {repr(desc)}")
        lines.append("    tables:")
        if not tables:
            lines.append("      - name: _placeholder")
            lines.append("        description: No tables in catalog; run bq_schema_catalog.py then re-run this script.")
        else:
            for t in tables:
                table_name = t.get("table", "unknown")
                cols = t.get("columns", [])
                lines.append(f"      - name: {table_name}")
                if cols:
                    lines.append("        columns:")
                    for c in cols:
                        name = c.get("name", "")
                        typ = c.get("type", "")
                        mode = c.get("mode", "NULLABLE")
                        lines.append(f"          - name: {name}")
                        lines.append(f"            description: \"{typ} ({mode})\"")
        lines.append("")
    return "\n".join(lines)


def build_minimal_sources_yml() -> str:
    """Build minimal sources with one placeholder table per source so dbt parses."""
    lines = [
        "# Generated by generate_dbt_sources.py (no catalog found). Run bq_schema_catalog.py then re-run this script.",
        "",
        "version: 2",
        "",
        "sources:",
    ]
    for layer in ("landing", "bronze", "silver", "gold"):
        desc = LAYER_DESCRIPTIONS[layer]

        if layer == "landing":
            schema_env = "BQ_DATASET_LANDING"
        elif layer == "bronze":
            schema_env = "BQ_DATASET_BRONZE"
        elif layer == "silver":
            schema_env = "BQ_DATASET_SILVER"
        else:
            schema_env = "BQ_DATASET_GOLD"

        lines.append(f"  - name: {layer}")
        lines.append('    database: "{{ env_var(\'BQ_PROJECT\', \'opentrace-prod-5ga4\') }}"')
        lines.append(
            "    schema: \"{{ env_var('" + schema_env + "', '" + layer + "') }}\""
        )
        lines.append(f"    description: {repr(desc)}")
        lines.append("    tables:")
        lines.append("      - name: _placeholder")
        lines.append("        description: Run bq_schema_catalog.py then generate_dbt_sources.py to fill from BQ.")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(description="Generate dbt sources.yml from BQ schema catalog")
    parser.add_argument("--refresh", action="store_true", help="Run bq_schema_catalog.py first to refresh the catalog")
    args = parser.parse_args()

    if args.refresh:
        _SCRIPTS_DIR = Path(__file__).resolve().parent
        if str(_SCRIPTS_DIR) not in sys.path:
            sys.path.insert(0, str(_SCRIPTS_DIR))
        try:
            from bq_schema_catalog import _load_dotenv, get_datasets_config, build_catalog
            from google.cloud import bigquery
            _load_dotenv()
            project = os.environ.get("BQ_PROJECT", "").strip()
            if not project:
                print("Set BQ_PROJECT (e.g. in data/local/.env)", file=sys.stderr)
                sys.exit(1)
            client = bigquery.Client(project=project)
            config = get_datasets_config()
            catalog = build_catalog(project, config, client)
            REPO_ROOT.joinpath("docs").mkdir(parents=True, exist_ok=True)
            CATALOG_PATH.write_text(json.dumps(catalog, indent=2), encoding="utf-8")
            print(f"Refreshed {CATALOG_PATH.relative_to(REPO_ROOT)}")
        except Exception as e:
            print(f"Refresh failed: {e}", file=sys.stderr)
            sys.exit(1)

    catalog = load_catalog()
    if catalog:
        content = build_sources_yml(catalog)
    else:
        print("No catalog at docs/bq_schema_catalog.json; writing minimal sources. Run bq_schema_catalog.py then re-run this script.", file=sys.stderr)
        content = build_minimal_sources_yml()

    DBT_SOURCES_PATH.parent.mkdir(parents=True, exist_ok=True)
    DBT_SOURCES_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {DBT_SOURCES_PATH.relative_to(REPO_ROOT)}")
    print("Done.")


if __name__ == "__main__":
    main()
